/// T1 行指向抽出。
///
/// 構文解析器に依存しない。未対応言語や構文誤りを含むファイルでも、この段階の結果だけは
/// 必ず得られる。これにより「対応していない言語のファイルがグラフから消える」ことを防ぐ
/// （docs/extraction.md 2、docs/decisions.md ADR-3 の代償 3）。
///
/// 走査は `ReadOnlySpan<byte>` に対して 1 回だけ行い、行ごとの文字列割り当てをしない。
/// 文字列を作るのは、実際に抽出した名前と綴りに限る。
module Srcnet.Extraction.LineScan

open System
open System.Buffers
open System.Collections.Generic
open System.Text
open System.Threading
open Srcnet.Core.Graph
open Srcnet.Text
open Srcnet.Extraction.Model

/// 根拠コメントの見出し。docs/graph-model.md 1 の `Note` に対応する。
let private noteTags = [| "TODO"; "FIXME"; "NOTE"; "HACK"; "SAFETY"; "XXX" |]

/// 生成コードのマーカー。大文字小文字を畳み込んでから比較する。
let private generatedMarkers =
  [| "do not edit"
     "do not modify"
     "autogenerated"
     "auto-generated"
     "automatically generated"
     "@generated"
     "generated by" |]

// --- バイト単位の述語 --------------------------------------------------------
// 識別子は「ASCII の英数字と `_`、および 0x80 以上のすべてのバイト」とする。
// 0x80 以上を一律に識別子の一部とみなすことで、UTF-8 の CJK 識別子が
// バイト境界で分断されない。復号は呼び出し側が済ませている前提である。

let inline private isIdentifierByte (b: byte) =
  (b >= 'a'B && b <= 'z'B)
  || (b >= 'A'B && b <= 'Z'B)
  || (b >= '0'B && b <= '9'B)
  || b = '_'B
  || b >= 0x80uy

let inline private isIdentifierStartByte (b: byte) =
  (b >= 'a'B && b <= 'z'B) || (b >= 'A'B && b <= 'Z'B) || b = '_'B || b >= 0x80uy

let inline private isBlank (b: byte) =
  b = ' 'B || b = '\t'B || b = '\r'B || b = 0x0Buy || b = 0x0Cuy

let private textOf (source: ReadOnlySpan<byte>) (start: int) (finish: int) =
  let from = max 0 start
  let until = min finish source.Length
  if until <= from then "" else Encoding.UTF8.GetString(source.Slice(from, until - from))

let private skipBlanks (line: ReadOnlySpan<byte>) (start: int) =
  let mutable index = max 0 start

  while index < line.Length && isBlank line[index] do
    index <- index + 1

  index

/// `start` から識別子を読み、終端位置を返す。識別子でなければ `start` を返す。
let private scanIdentifier (line: ReadOnlySpan<byte>) (start: int) =
  if start < 0 || start >= line.Length || not (isIdentifierStartByte line[start]) then max 0 start
  else
    let mutable index = start + 1

    while index < line.Length && isIdentifierByte line[index] do
      index <- index + 1

    index

/// 語が `start` に現れ、その直後が識別子の続きでないことを確かめる。
let private matchesWord (line: ReadOnlySpan<byte>) (start: int) (word: string) =
  if start < 0 || start + word.Length > line.Length then false
  else
    let mutable ok = true
    let mutable offset = 0

    while ok && offset < word.Length do
      if line[start + offset] <> byte word[offset] then ok <- false
      offset <- offset + 1

    ok && (start + word.Length >= line.Length || not (isIdentifierByte line[start + word.Length]))

let private matchesMarker (line: ReadOnlySpan<byte>) (start: int) (marker: string) =
  if start + marker.Length > line.Length then false
  else
    let mutable ok = true
    let mutable offset = 0

    while ok && offset < marker.Length do
      if line[start + offset] <> byte marker[offset] then ok <- false
      offset <- offset + 1

    ok

// --- 言語ごとの規則 ----------------------------------------------------------

/// 定義候補の語彙規則。`Keyword` の直後に現れる識別子を定義名として拾う。
[<Struct>]
type private DefinitionRule = { Keyword: string; Kind: NodeKind }

let private rule keyword kind : DefinitionRule = { Keyword = keyword; Kind = kind }

let private cLikeRules =
  [| rule "struct" Type
     rule "union" Type
     rule "enum" Type
     rule "class" Type
     rule "namespace" Module
     rule "interface" Type |]

let private rustRules =
  [| rule "fn" Function
     rule "struct" Type
     rule "enum" Type
     rule "trait" Type
     rule "union" Type
     rule "type" Type
     rule "mod" Module
     rule "const" Constant
     rule "static" Variable |]

let private pythonRules = [| rule "def" Function; rule "class" Type |]

let private goRules = [| rule "func" Function; rule "type" Type |]

let private javaRules =
  [| rule "class" Type
     rule "interface" Type
     rule "enum" Type
     rule "record" Type |]

let private scriptRules =
  [| rule "function" Function
     rule "class" Type
     rule "interface" Type
     rule "enum" Type
     rule "type" Type |]

let private fsharpRules =
  [| rule "type" Type
     rule "module" Module
     rule "namespace" Module
     rule "val" Function |]

let private definitionRules language =
  match language with
  | Language.C
  | Language.CHeader
  | Language.Cpp
  | Language.CppHeader
  | Language.ObjectiveC
  | Language.ObjectiveCpp -> cLikeRules
  | Language.Rust -> rustRules
  | Language.Python -> pythonRules
  | Language.Go -> goRules
  | Language.Java
  | Language.CSharp -> javaRules
  | Language.JavaScript
  | Language.TypeScript
  | Language.Tsx -> scriptRules
  | Language.FSharp
  | Language.FSharpSignature -> fsharpRules
  | _ -> Array.empty

/// 取り込みの綴りの囲み方。
type private ImportStyle =
  /// `#include <x>` / `#include "x"`。
  | Preprocessor
  /// `import x.y.z;` のように識別子とドットで綴る。
  | Dotted
  /// `use a::b::c;`。
  | ScopedPath
  /// `import "x"` / `source "x"` のように引用符で囲む。
  | Quoted
  /// `include x` のように行の残りをそのまま綴りとする。
  | Bare

[<Struct>]
type private ImportRule =
  { Word: string
    Style: ImportStyle
    Edge: EdgeKind }

let private importRules language =
  match language with
  | Language.C
  | Language.CHeader
  | Language.Cpp
  | Language.CppHeader
  | Language.ObjectiveC
  | Language.ObjectiveCpp
  | Language.Assembly ->
    [| { Word = "include"; Style = Preprocessor; Edge = Includes }
       { Word = "include_next"; Style = Preprocessor; Edge = Includes }
       { Word = "import"; Style = Preprocessor; Edge = Includes } |]
  | Language.Python ->
    [| { Word = "from"; Style = Dotted; Edge = Imports }
       { Word = "import"; Style = Dotted; Edge = Imports } |]
  | Language.Rust ->
    [| { Word = "use"; Style = ScopedPath; Edge = Imports }
       { Word = "mod"; Style = ScopedPath; Edge = Imports } |]
  | Language.Java -> [| { Word = "import"; Style = Dotted; Edge = Imports } |]
  | Language.CSharp -> [| { Word = "using"; Style = Dotted; Edge = Imports } |]
  | Language.Go
  | Language.JavaScript
  | Language.TypeScript
  | Language.Tsx -> [| { Word = "import"; Style = Quoted; Edge = Imports } |]
  | Language.Shell -> [| { Word = "source"; Style = Bare; Edge = Imports } |]
  | Language.Makefile ->
    [| { Word = "include"; Style = Bare; Edge = Imports }
       { Word = "-include"; Style = Bare; Edge = Imports } |]
  | Language.Kconfig -> [| { Word = "source"; Style = Quoted; Edge = Imports } |]
  | Language.CMake -> [| { Word = "include"; Style = Quoted; Edge = Imports } |]
  | Language.FSharp
  | Language.FSharpSignature -> [| { Word = "open"; Style = Dotted; Edge = Imports } |]
  | _ -> Array.empty

/// 行コメントの開始記号。
let private lineCommentMarkers language =
  match language with
  | Language.C
  | Language.CHeader
  | Language.Cpp
  | Language.CppHeader
  | Language.ObjectiveC
  | Language.ObjectiveCpp
  | Language.Rust
  | Language.Go
  | Language.Java
  | Language.CSharp
  | Language.JavaScript
  | Language.TypeScript
  | Language.Tsx
  | Language.FSharp
  | Language.FSharpSignature -> [| "//" |]
  | Language.Assembly -> [| "//"; ";" |]
  | Language.Python
  | Language.Shell
  | Language.Makefile
  | Language.CMake
  | Language.Kconfig
  | Language.Yaml
  | Language.Toml
  | Language.GnBuild
  | Language.Owners -> [| "#" |]
  | _ -> Array.empty

let private hasBlockComments language =
  match language with
  | Language.C
  | Language.CHeader
  | Language.Cpp
  | Language.CppHeader
  | Language.ObjectiveC
  | Language.ObjectiveCpp
  | Language.Rust
  | Language.Go
  | Language.Java
  | Language.CSharp
  | Language.JavaScript
  | Language.TypeScript
  | Language.Tsx -> true
  | _ -> false

/// 文字列リテラルの状態を追う言語か。行指向の走査で文字列を跨ぐ言語は対象外にする。
let private hasStringLiterals language =
  match language with
  | Language.Makefile
  | Language.Kconfig
  | Language.Owners
  | Language.PlainText
  | Language.Markdown
  | Language.Unknown -> false
  | _ -> true

// --- 綴りの取り出し ----------------------------------------------------------

/// 引用符（`"`、`'`、`<`）で囲まれた綴りを取り出す。
let private quotedSpelling (line: ReadOnlySpan<byte>) (from: int) =
  let mutable index = max 0 from
  let mutable result = ValueNone

  while result.IsNone && index < line.Length do
    let b = line[index]

    if b = '"'B || b = '\''B || b = '<'B then
      let closing = if b = '<'B then '>'B else b
      let mutable finish = index + 1

      while finish < line.Length && line[finish] <> closing do
        finish <- finish + 1

      if finish < line.Length then result <- ValueSome(struct (index + 1, finish))
      else index <- line.Length
    else index <- index + 1

  result

/// ドット区切りの綴り（`java.util.List`）を取り出す。
let private dottedSpelling (line: ReadOnlySpan<byte>) (from: int) =
  let start = skipBlanks line from

  if start >= line.Length || not (isIdentifierStartByte line[start]) then ValueNone
  else
    let mutable finish = start

    while finish < line.Length && (isIdentifierByte line[finish] || line[finish] = '.'B) do
      finish <- finish + 1

    ValueSome(struct (start, finish))

/// `a::b::c` 形式の綴りを取り出す。
let private scopedSpelling (line: ReadOnlySpan<byte>) (from: int) =
  let start = skipBlanks line from

  if start >= line.Length || not (isIdentifierStartByte line[start]) then ValueNone
  else
    let mutable finish = start

    while finish < line.Length && (isIdentifierByte line[finish] || line[finish] = ':'B) do
      finish <- finish + 1

    // 末尾に残ったコロンは区切り記号であって綴りの一部ではない。
    while finish > start && line[finish - 1] = ':'B do
      finish <- finish - 1

    ValueSome(struct (start, finish))

/// 行末までの綴り。末尾の空白は落とす。
let private bareSpelling (line: ReadOnlySpan<byte>) (from: int) =
  let start = skipBlanks line from
  let mutable finish = line.Length

  while finish > start && isBlank line[finish - 1] do
    finish <- finish - 1

  if finish <= start then ValueNone else ValueSome(struct (start, finish))

/// 行の中で `TAG:` の形の根拠コメントを探す。見つかったら見出しと本文開始位置を返す。
let private findNoteTag (line: ReadOnlySpan<byte>) (from: int) (until: int) =
  let mutable index = max 0 from
  let stop = min until line.Length
  let mutable found = ValueNone

  while found.IsNone && index < stop do
    if isIdentifierStartByte line[index] && (index = 0 || not (isIdentifierByte line[index - 1])) then
      let mutable tagIndex = 0

      while found.IsNone && tagIndex < noteTags.Length do
        let tag = noteTags[tagIndex]

        if matchesWord line index tag then
          let after = skipBlanks line (index + tag.Length)
          if after < stop && line[after] = ':'B then found <- ValueSome(struct (tag, index, after + 1))

        tagIndex <- tagIndex + 1

    index <- index + 1

  found

// --- 走査 --------------------------------------------------------------------

/// T1 の走査結果。
type ScanResult =
  { Symbols: ExtractedSymbol[]
    References: ExtractedReference[]
    /// 生成物マーカーを先頭付近に持つ。
    Generated: bool
    /// 行数・行長の上限に達して打ち切った。
    Truncated: bool
    /// 走査した論理的な行数。
    LineCount: int }

/// 1 行分の区分。コメントとコードの範囲を、行内の相対位置で表す。
[<Struct>]
type private LineLayout =
  { CodeStart: int
    CodeEnd: int
    MaskedCode: bool
    CommentStart: int
    CommentEnd: int }

/// 行をコード部分とコメント部分に分ける。
///
/// 完全な字句解析はしない。文字列リテラル内の `//` を誤ってコメント開始と見なさない
/// 程度の状態だけを持つ。`inBlockComment` は行をまたいで持ち越す。
let private layoutOf
  (line: ReadOnlySpan<byte>)
  (markers: string[])
  (blockComments: bool)
  (strings: bool)
  (inBlockComment: bool)
  (code: Span<byte>)
  =
  let length = line.Length
  let mutable blockOpen = inBlockComment
  let mutable blockStart = if inBlockComment then 0 else -1
  let mutable codeEnd = length
  let mutable maskedCode = false
  let mutable commentStart = if inBlockComment then 0 else -1
  let mutable commentEnd = if inBlockComment then length else -1
  let mutable index = 0
  let mutable quote = 0uy

  while index < length do
    let b = line[index]

    if blockOpen then
      if b = '*'B && index + 1 < length && line[index + 1] = '/'B then
        blockOpen <- false
        if commentStart = blockStart then commentEnd <- index + 2
        if not maskedCode then line.CopyTo code
        code.Slice(blockStart, index + 2 - blockStart).Fill ' 'B
        maskedCode <- true

        index <- index + 2
      else index <- index + 1
    elif quote <> 0uy then
      if b = '\\'B then index <- index + 2
      else
        if b = quote then quote <- 0uy
        index <- index + 1
    elif blockComments && b = '/'B && index + 1 < length && line[index + 1] = '*'B then
      blockOpen <- true
      blockStart <- index

      if commentStart < 0 then
        commentStart <- index
        commentEnd <- length

      index <- index + 2
    elif strings && (b = '"'B || b = '\''B) then
      quote <- b
      index <- index + 1
    else
      let mutable matched = false
      let mutable markerIndex = 0

      while not matched && markerIndex < markers.Length do
        if matchesMarker line index markers[markerIndex] then matched <- true
        markerIndex <- markerIndex + 1

      if matched then
        if commentStart < 0 then
          commentStart <- index
          commentEnd <- length

        codeEnd <- index
        index <- length
      else index <- index + 1

  if blockOpen then
    if not maskedCode then line.CopyTo code
    code.Slice(blockStart, length - blockStart).Fill ' 'B
    maskedCode <- true

  let layout =
    { CodeStart = 0
      CodeEnd = codeEnd
      MaskedCode = maskedCode
      CommentStart = commentStart
      CommentEnd = if commentStart < 0 then -1 else min commentEnd length }

  struct (layout, blockOpen)

/// テキスト ファイルを行単位で走査し、取り込み・定義候補・根拠コメントを抽出する。
///
/// `source` は復号済みの UTF-8 バイト列。結果の位置は `source` 内のバイト位置である。
let private runCore
  (language: Language)
  (source: ReadOnlySpan<byte>)
  (inheritedFlags: NodeFlags)
  (cancellation: CancellationToken)
  (codeBuffer: byte[])
  : ScanResult =
  let symbols = List<ExtractedSymbol>()
  let references = List<ExtractedReference>()
  let rules = definitionRules language
  let imports = importRules language
  let markers = lineCommentMarkers language
  let blockComments = hasBlockComments language
  let strings = hasStringLiterals language

  let flags =
    inheritedFlags &&& (NodeFlags.Vendored ||| NodeFlags.Generated ||| NodeFlags.Test)

  // 定義候補には定義の印を付ける。行指向の推定なのでエッジの確度は `EXTRACTED` に留まるが、
  // 「宣言だけ」と区別できないと `DEFINES` の経路がまったく生まれない。
  let definitionFlags = flags ||| NodeFlags.Definition

  let mutable generated = false
  let mutable truncated = false
  let mutable lineNumber = 0
  let mutable position = 0
  let mutable inBlockComment = false

  while position < source.Length && lineNumber < Limits.MaxLines do
    cancellation.ThrowIfCancellationRequested()
    let remaining = source.Slice position
    let breakIndex = remaining.IndexOfAny('\n'B, '\r'B)
    let rawLength = if breakIndex < 0 then remaining.Length else breakIndex

    let advance =
      if breakIndex < 0 then remaining.Length
      elif
        remaining[breakIndex] = '\r'B
        && breakIndex + 1 < remaining.Length
        && remaining[breakIndex + 1] = '\n'B
      then
        breakIndex + 2
      else breakIndex + 1

    // 極端に長い行は走査対象を上限で打ち切る。読み飛ばしても走査自体は継続する。
    let scanLength =
      if rawLength > Limits.MaxLineBytes then
        truncated <- true
        Limits.MaxLineBytes
      else rawLength

    let lineStart = position
    let line = remaining.Slice(0, scanLength)
    lineNumber <- lineNumber + 1

    let struct (layout, blockOpen) =
      layoutOf line markers blockComments strings inBlockComment (Span(codeBuffer, 0, scanLength))

    inBlockComment <- blockOpen

    let codeStart = layout.CodeStart
    let codeEnd = layout.CodeEnd
    let hasCode = codeEnd > codeStart

    // --- 生成物マーカー ---
    // 探索範囲を先頭に限る。本文にだけ `DO NOT EDIT` を含むファイルを生成扱いにしない。
    if
      not generated
      && lineNumber <= Limits.GeneratedMarkerScanLines
      && lineStart < Limits.GeneratedMarkerScanBytes
      && layout.CommentStart >= 0
    then
      let folded =
        let finish = min (lineStart + layout.CommentEnd) Limits.GeneratedMarkerScanBytes
        Unicode.caseFold (textOf source (lineStart + layout.CommentStart) finish)

      let mutable markerIndex = 0

      while not generated && markerIndex < generatedMarkers.Length do
        if folded.Contains(generatedMarkers[markerIndex], StringComparison.Ordinal) then generated <- true
        markerIndex <- markerIndex + 1

    // --- 根拠コメント ---
    if layout.CommentStart >= 0 then
      match findNoteTag line layout.CommentStart layout.CommentEnd with
      | ValueNone -> ()
      | ValueSome(struct (tag, tagStart, bodyStart)) ->
        if symbols.Count >= Limits.MaxSymbolsPerFile then truncated <- true
        else
          let bodyFrom = skipBlanks line bodyStart
          let raw = textOf source (lineStart + bodyFrom) (lineStart + layout.CommentEnd)
          let trimmed = raw.TrimEnd([| ' '; '\t'; '*'; '/'; '\r' |])

          let body = truncateText Limits.MaxNoteTextLength trimmed

          let qualified = if body = "" then tag else tag + ": " + body

          symbols.Add
            { Kind = Note
              Name = tag
              QualifiedName = normalizeName qualified
              Parent = -1
              Ordinal = 0u
              StartLine = lineNumber
              EndLine = lineNumber
              StartByte = lineStart + tagStart
              EndByte = lineStart + layout.CommentEnd
              Flags = flags
              Doc = ByteRange.create (lineStart + bodyFrom) (lineStart + layout.CommentEnd)
              Condition = "" }

    if hasCode then
      let code =
        if layout.MaskedCode then ReadOnlySpan(codeBuffer, 0, codeEnd)
        else line.Slice(0, codeEnd)

      let first = skipBlanks code codeStart

      // --- 取り込み ---
      // コード部分の先頭からのみ判定する。コメントや文字列の途中にある綴りは拾わない。
      if imports.Length > 0 && first < codeEnd then
        let struct (keywordStart, isPreprocessor) =
          if code[first] = '#'B then struct (skipBlanks code (first + 1), true)
          else struct (first, false)

        let mutable ruleIndex = 0

        while ruleIndex < imports.Length do
          let importRule = imports[ruleIndex]

          let applies =
            match importRule.Style with
            | Preprocessor -> isPreprocessor
            | _ -> not isPreprocessor

          if applies && matchesWord code keywordStart importRule.Word then
            let after = keywordStart + importRule.Word.Length

            let spelling =
              match importRule.Style with
              | Preprocessor ->
                let start = skipBlanks code after

                if start < code.Length && (code[start] = '"'B || code[start] = '<'B) then
                  quotedSpelling code start
                else bareSpelling code start
              | Quoted -> quotedSpelling code after
              | Dotted -> dottedSpelling code after
              | ScopedPath -> scopedSpelling code after
              | Bare -> bareSpelling code after

            match spelling with
            | ValueNone -> ()
            | ValueSome(struct (spellStart, spellEnd)) ->
              if references.Count >= Limits.MaxReferencesPerFile then truncated <- true
              else
                let raw = textOf source (lineStart + spellStart) (lineStart + spellEnd)
                let target = normalizeName raw

                if target <> "" then
                  references.Add
                    { Source = -1
                      Kind = importRule.Edge
                      Target = target
                      Qualifier = ""
                      Language = language
                      StartByte = lineStart + spellStart
                      EndByte = lineStart + spellEnd
                      Line = lineNumber
                      Stage = 0uy
                      Confidence = Extracted }

            ruleIndex <- imports.Length
          else ruleIndex <- ruleIndex + 1

      // --- 前処理指令による定義候補 ---
      if first < codeEnd && code[first] = '#'B then
        let directive = skipBlanks code (first + 1)

        if matchesWord code directive "define" then
          let nameStart = skipBlanks code (directive + 6)
          let nameEnd = scanIdentifier code nameStart

          if nameEnd > nameStart then
            if symbols.Count >= Limits.MaxSymbolsPerFile then truncated <- true
            else
              // 名前の直後に空白なく `(` が続くものだけを関数形式マクロとする。
              let isFunctionLike = nameEnd < codeEnd && code[nameEnd] = '('B

              symbols.Add
                { Kind = (if isFunctionLike then Macro else Constant)
                  Name = normalizeName (textOf source (lineStart + nameStart) (lineStart + nameEnd))
                  QualifiedName = normalizeName (textOf source (lineStart + nameStart) (lineStart + nameEnd))
                  Parent = -1
                  Ordinal = 0u
                  StartLine = lineNumber
                  EndLine = lineNumber
                  StartByte = lineStart + first
                  EndByte = lineStart + codeEnd
                  Flags = definitionFlags
                  Doc = ByteRange.empty
                  Condition = "" }
      elif rules.Length > 0 then
        // --- 語彙規則による定義候補 ---
        // 修飾子（`public`、`static`、`export` など）を最大 4 語まで読み飛ばす。
        let mutable cursor = first
        let mutable matched = false
        let mutable skips = 0

        while not matched && skips <= 4 && cursor < codeEnd do
          let mutable ruleIndex = 0

          while not matched && ruleIndex < rules.Length do
            let definitionRule = rules[ruleIndex]

            if matchesWord code cursor definitionRule.Keyword then
              let nameStart = skipBlanks code (cursor + definitionRule.Keyword.Length)
              let nameEnd = scanIdentifier code nameStart
              matched <- true

              if nameEnd > nameStart then
                if symbols.Count >= Limits.MaxSymbolsPerFile then truncated <- true
                else
                  let name = normalizeName (textOf source (lineStart + nameStart) (lineStart + nameEnd))

                  symbols.Add
                    { Kind = definitionRule.Kind
                      Name = name
                      QualifiedName = name
                      Parent = -1
                      Ordinal = 0u
                      StartLine = lineNumber
                      EndLine = lineNumber
                      StartByte = lineStart + cursor
                      EndByte = lineStart + codeEnd
                      Flags = definitionFlags
                      Doc = ByteRange.empty
                      Condition = "" }

            ruleIndex <- ruleIndex + 1

          if not matched then
            let wordEnd = scanIdentifier code cursor

            if wordEnd = cursor then cursor <- codeEnd
            else
              cursor <- skipBlanks code wordEnd
              skips <- skips + 1

      // --- 言語固有の構造 ---
      match language with
      | Language.Kconfig ->
        let keyword = skipBlanks code codeStart

        let skip =
          if matchesWord code keyword "config" then 6
          elif matchesWord code keyword "menuconfig" then 10
          else 0

        if skip > 0 then
          let nameStart = skipBlanks code (keyword + skip)
          let nameEnd = scanIdentifier code nameStart

          if nameEnd > nameStart then
            if symbols.Count >= Limits.MaxSymbolsPerFile then truncated <- true
            else
              let name = normalizeName (textOf source (lineStart + nameStart) (lineStart + nameEnd))

              symbols.Add
                { Kind = ConfigSymbol
                  Name = name
                  QualifiedName = name
                  Parent = -1
                  Ordinal = 0u
                  StartLine = lineNumber
                  EndLine = lineNumber
                  StartByte = lineStart + keyword
                  EndByte = lineStart + codeEnd
                  Flags = definitionFlags
                  Doc = ByteRange.empty
                  Condition = "" }
      | Language.Makefile ->
        // 行頭から始まる `target:` と `VAR =` を拾う。recipe（TAB 始まり）と継続行は除く。
        if codeStart = 0 && not (isBlank line[0]) then
          // Makefile の名前は `-` と `.` を含む（`obj-y`、`main.o`）。識別子の規則を広げる。
          let mutable nameEnd = 0

          while nameEnd < codeEnd
                && (isIdentifierByte code[nameEnd] || code[nameEnd] = '-'B || code[nameEnd] = '.'B) do
            nameEnd <- nameEnd + 1

          if nameEnd > 0 then
            let after = skipBlanks code nameEnd

            let kind =
              if after >= codeEnd then ValueNone
              elif code[after] = ':'B && after + 1 < codeEnd && code[after + 1] = '='B then ValueSome Variable
              elif code[after] = ':'B then ValueSome BuildTarget
              elif code[after] = '='B then ValueSome Variable
              elif (code[after] = '+'B || code[after] = '?'B)
                   && after + 1 < codeEnd
                   && code[after + 1] = '='B then
                ValueSome Variable
              else ValueNone

            match kind with
            | ValueNone -> ()
            | ValueSome nodeKind ->
              if symbols.Count >= Limits.MaxSymbolsPerFile then truncated <- true
              else
                let name = normalizeName (textOf source lineStart (lineStart + nameEnd))

                symbols.Add
                  { Kind = nodeKind
                    Name = name
                    QualifiedName = name
                    Parent = -1
                    Ordinal = 0u
                    StartLine = lineNumber
                    EndLine = lineNumber
                    StartByte = lineStart
                    EndByte = lineStart + codeEnd
                    Flags = definitionFlags
                    Doc = ByteRange.empty
                    Condition = "" }
      | Language.Assembly ->
        // 行頭のラベル `name:` を関数の入口とみなす。
        if codeStart = 0 && scanLength > 0 && not (isBlank line[0]) then
          let nameEnd = scanIdentifier code 0

          if nameEnd > 0 && nameEnd < codeEnd && code[nameEnd] = ':'B then
            if symbols.Count >= Limits.MaxSymbolsPerFile then truncated <- true
            else
              let name = normalizeName (textOf source lineStart (lineStart + nameEnd))

              symbols.Add
                { Kind = Function
                  Name = name
                  QualifiedName = name
                  Parent = -1
                  Ordinal = 0u
                  StartLine = lineNumber
                  EndLine = lineNumber
                  StartByte = lineStart
                  EndByte = lineStart + nameEnd
                  Flags = definitionFlags
                  Doc = ByteRange.empty
                  Condition = "" }
      | _ -> ()

    position <- position + advance

  if position < source.Length then truncated <- true

  { Symbols = symbols.ToArray()
    References = references.ToArray()
    Generated = generated
    Truncated = truncated
    LineCount = if position < source.Length then Decoding.countLines source else lineNumber }

let runWithCancellation
  (language: Language)
  (source: ReadOnlySpan<byte>)
  (inheritedFlags: NodeFlags)
  (cancellation: CancellationToken)
  =
  cancellation.ThrowIfCancellationRequested()
  let buffer = ArrayPool<byte>.Shared.Rent(min source.Length Limits.MaxLineBytes)

  try
    let result = runCore language source inheritedFlags cancellation buffer
    cancellation.ThrowIfCancellationRequested()
    result
  finally
    ArrayPool<byte>.Shared.Return buffer

let run (language: Language) (source: ReadOnlySpan<byte>) (inheritedFlags: NodeFlags) =
  runWithCancellation language source inheritedFlags CancellationToken.None
