<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Srcnet.Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Blake3.fs" />
        <Compile Include="Graph.fs" />
        <Compile Include="Paths.fs" />
        <Compile Include="Ids.fs" />
        <Compile Include="Diagnostics.fs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Srcnet.Text/Srcnet.Text.fsproj" />
    </ItemGroup>

</Project>
