<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Srcnet.Text</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Unicode.fs" />
        <Compile Include="Encodings.fs" />
        <Compile Include="Decoding.fs" />
        <Compile Include="Sanitize.fs" />
        <Compile Include="Words.fs" />
    </ItemGroup>

</Project>
